### ISSUE TITLE
Error logs

### ISSUE THREAD

**Issue by legendksk** [SomethingFromSomewhere/Custom-Rounds#2]
Hello;
log files are full of these errors
What is the reason ? How can i solve it?

L 05/20/2020 - 04:15:20: Failed to auto generate config for CR_Votes.smx, make sure the directory has write permission.
L 05/20/2020 - 04:15:20: Failed to auto generate config for CR_Misc.smx, make sure the directory has write permission.
L 05/20/2020 - 04:15:20: Failed to auto generate config for CR_Weapons.smx, make sure the directory has write permission.
L 05/20/2020 - 04:15:20: Failed to auto generate config for CR_Menu.smx, make sure the directory has write permission.
L 05/20/2020 - 04:15:20: Failed to auto generate config for CR_Intervals.smx, make sure the directory has write permission.

Thanks, regards.

**Comment by Erik-97** [comment]
Create a folder called "custom_rounds" inside csgo/cfg/sourcemod/
